apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{"alb.ingress.kubernetes.io/scheme":"internet-facing","alb.ingress.kubernetes.io/target-type":"ip"},"name":"astro-mern-ingress","namespace":"astro-mern-ns"},"spec":{"ingressClassName":"alb","rules":[{"http":{"paths":[{"backend":{"service":{"name":"astro-mern-service","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]}}
  creationTimestamp: "2025-12-29T09:59:58Z"
  finalizers:
  - ingress.k8s.aws/resources
  generation: 1
  name: astro-mern-ingress
  namespace: astro-mern-ns
  resourceVersion: "43271"
  uid: d8766d71-a2f0-4b38-bc6c-c57eaa20e4c8
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - backend:
          service:
            name: astro-mern-service
            port:
              number: 80
        path: /
        pathType: Prefix
status:
  loadBalancer: {}
